server:
  port: 8000  # API Gateway port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - TokenRelay=

        - id: post-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/posts/**
          filters:
            - TokenRelay=

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: apigateway-client
            client-secret: YrH1iZmCVT6LcZWNCftTLnbXUswdOgMz
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/social-media

# Enable debugging logs for troubleshooting
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG

# Enable Spring Boot Actuator for monitoring
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
