spring:
  application:
    name: postservice
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          default_schema: user-service
server:
  port: 8082
  servlet:
    context-path: /
#logging:
#  level:
#    org:
#      springframework: DEBUG
#      hibernate: DEBUG