spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          default_schema: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/social-media
#      client:
#        registration:
#          keycloak:
#            client-id: user-service-client
#            client-secret: virMMZ3tzv7ytPYUMqbhDyeqT9zOm2sx
#            authorization-grant-type: client_credentials
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/social-media
server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    org:
      springframework: DEBUG
#      hibernate: DEBUG
